### ISSUE TITLE
Sync Freeze module between servers + {server} placeholder

### ISSUE THREAD

**Issue by LuckserSky34** [PulsirDevelopment/Lunar#11]
Option to sync messages of freeze module between all server using redis
and support for **{server}** placeholder in **STAFF-FROZEN, STAFF-UNFROZE, QUIT** messages.

**Comment by KacpersDev** [comment]
Freeze chat won't be synced & Placeholders are added though.

**Comment by LuckserSky34** [comment]
i'm not referring about freeze chat i only want to sync message when you freeze an player, like others plugin do.

**Comment by KacpersDev** [comment]
Okay. Ill add it

**Comment by KacpersDev** [comment]
Feature is done, will be released in the newest update.
