### ISSUE TITLE
Server placeholder and frozen player chat

### ISSUE THREAD

**Issue by LuckserSky34** [PulsirDevelopment/Lunar#3]
Add a new placeholder to show staff member server, something like this: [SC] [%SERVER%] %staff%: %message%

New chat module to show frozen player messages in chat, so you can communicate with him if something happen, but you need 
to have the inventory menu off, to work. for example [Freeze] [%SERVER%]  %player%: %message%

**Comment by KacpersDev** [comment]
Both of your issues have been accepted and will be worked on tomorrow. 

Thank you for submitting! 

I will close issue with comment when an update will happen on SpigotMC & BuildByBit

**Comment by KacpersDev** [comment]
Issue has been fixed with new version (1.0.8)
