### ISSUE TITLE
Freeze mode additions

### ISSUE THREAD

**Issue by LuckserSky34** [PulsirDevelopment/Lunar#4]
add a message to know which staff froze the player and show to other staffs members
example: **[Freeze] {server} %player% has been frozen by %staff%**

and other message when the player gets unfrozen: **[Freeze] {server} %player% has been unfrozen by %staff% after %time_frozen%**(seconds,minutes)

if the player disconnect in freeze mode show an alert message to all staff members:  **[Freeze] {server} %player% has been disconnected while frozen**. so if the player disconnect you can ban the player adding a hover command in the message to execute the ban for example /ban %player% 30d disconnect in a revision

**Comment by KacpersDev** [comment]
Issue has been fixed in the newest version (1.0.9)
