### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by LuckserSky34** [PulsirDevelopment/Lunar#5]
1. Option to change the head slot in staff online inventory and support for head skin
2. placeholder to show the session playtime of the staff member in online staff menu for example Session Time: 1h 30m
3. Option to teleport to staff member when you click them in online staff menu
4. Placeholder to show if staff is in modmode in online staff menu
5. item to toggle vanish mode in /mod hotbar for example when vanish is on you have an green_dye and a grey_dye  when vanish is off
7. a message to show to other staff enter in /mod for example: [%staff% has enter in modmode]
8. fix random teleport to teleport only to online players because you can teleport to yourself
9. add option to add /mod status in staffbar for example: Status: Mod Mode an when you are outside /mod show Status: Normal
10. add an option to show staff-bar when you are in vanish and not only in /mod
11. ability to staff in vanish be able to see other staff in vanish - make staff Transparent/partial invisibility instead to completely vanish. 
13. Option to disable vanish on join or remember /vanish status when rejoin

**Comment by KacpersDev** [comment]
Thanks for the feature. Most will get added, some will be in different plugin such as (playtime).

**Comment by KacpersDev** [comment]
Some features have been added in newest update (2.0.3). Rest will be added on days.
