### ISSUE TITLE
{server} shows wrong

### ISSUE THREAD

**Issue by LuckserSky34** [PulsirDevelopment/Lunar#7]
{server} placeholder shows spigot brand instead server name, so my request is to add in config 
an section to add server-ID name for example: 

Server-ID: "Survival" 

so when the staff talk in staff chat or other message with server-id placeholder this gonna show
the exact server name instead the spigot brand like paper o others

**Comment by KacpersDev** [comment]
Feature Approved. 

What the plugin is getting the name from spigot.yml i believe or server.properties.

**Comment by KacpersDev** [comment]
Issue has been resolved.
